fix: Pass device parameter to _interpolate_recursive instead of using model.device
- LatentBrownianBridgeModel doesn't have .device attribute
- Pass device as parameter from interpolate() method
- Use device parameter instead of model.device in recursive mode
- Fixes AttributeError: 'LatentBrownianBridgeModel' object has no attribute 'device'